# Force deploy

deployment:
  tasks:
    - export DEPLOYPATH=/home/inspgdgt/public_html
    - export REPOPATH=/home/inspgdgt/repositories/InspiroStudio
    - cd $REPOPATH
    - npm install
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
